controller_manager:
  ros__parameters:
    update_rate: 1000 #Hz
    use_sim_time: true

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints: 
      - Joint_1
      - Joint_2
      - Joint_3
      - Joint_4
      - Joint_5
      